version = "1"

name = "Lua"
description = "Run static analysis on lua codebases"
category = "language"
visibility = "public"

[analyzer]
  command = "cd /app && lua ./src/main.lua"

[build]
  image = "cytopia/ansible-lint:5"
  steps = """cp -r . /app
  apk add shadow git grep"""