version = "1"

name = "Lua"
description = "Run static analysis on lua codebases"
category = "language"
visibility = "public"
analysis_command = "echo $LUA_PATH && lua ./src/main.lua"

[analyzer]
  command = "echo $LUA_PATH && lua ./src/main.lua"

[build]
  image = "ubuntu:18.04"
  steps = """
	apt-get update
	cp -R . /app
  apt-get install --yes --no-install-recommends git grep openssh-server
	apt-get install --yes lua5.3
	apt-get install --yes luarocks
  apt-get install --yes liblua5.3-dev
	cd /app
	luarocks install luafilesystem
	luarocks install luacheck
	luarocks install lua-path
  chmod +x ./hacc
  ./hacc
  """
