version = "1"

name = "Lua"
description = "Run static analysis on lua codebases"
category = "language"
visibility = "public"
analysis_command = "lua ./src/main.lua"

[analyzer]
  command = "lua ./src/main.lua"

[build]
  image = "ubuntu:18.04"
  steps = """
	apt-get update
	cp -R . /app
	apt-get install --yes lua5.3
	apt-get install luarocks
	cd /app
	luarocks install luafilesystem
	luarocks install luacheck
	luarocks install lua-path
	luarocks path --bin >> ~/.bash_profile
  """